version: "3.7"
services:
    db:
        image: postgres:14.2
        container_name: db
        restart: always
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_USER: api_root
            POSTGRES_PASSWORD: P@$$vv0RD
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - database_data:/var/lib/postgresql/data
            - ./MoscowApi/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        depends_on:
            - app
        ports:
            - 7000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs:/var/log/nginx
    app:
        build:
            context: .
            dockerfile: ./MoscowApi/dockerfile
        container_name: app
        # ports:
        #     - 7001:7001
        restart: always
        depends_on:
            - db
        links:
            - db
volumes:
    database_data:
        driver: local
